export { default as LoginScreen } from './Login'
export { default as HomeScreen } from './Home'
export { default as RegistrationScreen } from './Register'
export { default as AddDataScreen } from './AddData'
export { default as SeeDataScreen } from './SeeData'
export { default as SeeProgressionScreen } from './SeeProgression'
